project:
  type: website
  output-dir: docs

website:
  title: "John's Data Science Portfolio"
  description: "A showcase of my data sciene projects and learning journey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Blog.qmd
        text: Blog
      - text: "Projects"
        menu:
          - text: "All Projects"
            href: projects/index.md
          - text: "Final Project - Overview"
            href: projects/final-project/index.qmd
          - text: "Final Project - Technical Report" 
            href: projects/final-project/report.qmd
          - text: "Final Project - Tutorial"
            href: projects/final-project/tutorial.qmd
          - text: "Final Project - API Reference" 
            href: projects/final-project/api.qmd
          
            

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



